image: gitpod/workspace-dotnet-vnc

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore 
      dotnet build StudentNetProject.sln
ports:
  - port: 5000
    onOpen: open-preview
